-- sql/seed_state.sql — 州略号 <-> 州名 <-> FIPS の橋渡し
--
-- provider / provider_drug は略号（FL）、geo_drug は州名フル（Florida）を持つ。
-- 州名は geo_drug.prscrbr_geo_desc の実値と完全一致させてある（2024年データで突合済み）。
-- is_state = TRUE は 50州 + DC のみ。準州・軍事郵便・Unknown/Foreign は FALSE で、
-- 「州別ランキング」ではこれらを除外する。
--
--   bq query --use_legacy_sql=false < sql/seed_state.sql

DELETE FROM partd.state WHERE TRUE;

INSERT INTO partd.state (state_abrvtn, state_name, state_fips, region, is_state) VALUES
  ('AL', 'Alabama', '01', 'South', TRUE),
  ('AK', 'Alaska', '02', 'West', TRUE),
  ('AZ', 'Arizona', '04', 'West', TRUE),
  ('AR', 'Arkansas', '05', 'South', TRUE),
  ('CA', 'California', '06', 'West', TRUE),
  ('CO', 'Colorado', '08', 'West', TRUE),
  ('CT', 'Connecticut', '09', 'Northeast', TRUE),
  ('DE', 'Delaware', '10', 'South', TRUE),
  ('DC', 'District of Columbia', '11', 'South', TRUE),
  ('FL', 'Florida', '12', 'South', TRUE),
  ('GA', 'Georgia', '13', 'South', TRUE),
  ('HI', 'Hawaii', '15', 'West', TRUE),
  ('ID', 'Idaho', '16', 'West', TRUE),
  ('IL', 'Illinois', '17', 'Midwest', TRUE),
  ('IN', 'Indiana', '18', 'Midwest', TRUE),
  ('IA', 'Iowa', '19', 'Midwest', TRUE),
  ('KS', 'Kansas', '20', 'Midwest', TRUE),
  ('KY', 'Kentucky', '21', 'South', TRUE),
  ('LA', 'Louisiana', '22', 'South', TRUE),
  ('ME', 'Maine', '23', 'Northeast', TRUE),
  ('MD', 'Maryland', '24', 'South', TRUE),
  ('MA', 'Massachusetts', '25', 'Northeast', TRUE),
  ('MI', 'Michigan', '26', 'Midwest', TRUE),
  ('MN', 'Minnesota', '27', 'Midwest', TRUE),
  ('MS', 'Mississippi', '28', 'South', TRUE),
  ('MO', 'Missouri', '29', 'Midwest', TRUE),
  ('MT', 'Montana', '30', 'West', TRUE),
  ('NE', 'Nebraska', '31', 'Midwest', TRUE),
  ('NV', 'Nevada', '32', 'West', TRUE),
  ('NH', 'New Hampshire', '33', 'Northeast', TRUE),
  ('NJ', 'New Jersey', '34', 'Northeast', TRUE),
  ('NM', 'New Mexico', '35', 'West', TRUE),
  ('NY', 'New York', '36', 'Northeast', TRUE),
  ('NC', 'North Carolina', '37', 'South', TRUE),
  ('ND', 'North Dakota', '38', 'Midwest', TRUE),
  ('OH', 'Ohio', '39', 'Midwest', TRUE),
  ('OK', 'Oklahoma', '40', 'South', TRUE),
  ('OR', 'Oregon', '41', 'West', TRUE),
  ('PA', 'Pennsylvania', '42', 'Northeast', TRUE),
  ('RI', 'Rhode Island', '44', 'Northeast', TRUE),
  ('SC', 'South Carolina', '45', 'South', TRUE),
  ('SD', 'South Dakota', '46', 'Midwest', TRUE),
  ('TN', 'Tennessee', '47', 'South', TRUE),
  ('TX', 'Texas', '48', 'South', TRUE),
  ('UT', 'Utah', '49', 'West', TRUE),
  ('VT', 'Vermont', '50', 'Northeast', TRUE),
  ('VA', 'Virginia', '51', 'South', TRUE),
  ('WA', 'Washington', '53', 'West', TRUE),
  ('WV', 'West Virginia', '54', 'South', TRUE),
  ('WI', 'Wisconsin', '55', 'Midwest', TRUE),
  ('WY', 'Wyoming', '56', 'West', TRUE),
  ('PR', 'Puerto Rico', '72', 'Territory', FALSE),
  ('VI', 'Virgin Islands', '78', 'Territory', FALSE),
  ('GU', 'Guam', '66', 'Territory', FALSE),
  ('AS', 'American Samoa', '60', 'Territory', FALSE),
  ('MP', 'Northern Mariana Islands', '69', 'Territory', FALSE),
  ('FM', 'Federated States of Micronesia', '64', 'Territory', FALSE),
  ('AA', 'Armed Forces Central/South America', NULL, 'Armed Forces', FALSE),
  ('AE', 'Armed Forces Europe', NULL, 'Armed Forces', FALSE),
  ('AP', 'Armed Forces Pacific', NULL, 'Armed Forces', FALSE),
  ('XX', 'Unknown', NULL, 'Unknown', FALSE),
  ('ZZ', 'Foreign Country', NULL, 'Foreign', FALSE);
